# Project Name
TARGET = OmniSeed

# Sources
CPP_SOURCES = OmniSeed.cpp \
keypad.cpp 

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
